name: Update package metadata
on:
  schedule:
    - cron: '0 0 * * *'   # каждый день
  workflow_dispatch:

permissions:
  contents: write  # <- важно, без этого push не пройдет

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package metadata
          branch: main
          push_options: --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
