name: "Generate package metadata"
on:
  workflow_dispatch:    # запуск вручную
  schedule:
    - cron: '0 2 * * *' # раз в день в 2:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Установка Nix
      - uses: DeterminateSystems/nix-installer-action@v4

      - name: Generate JSON
        run: |
          mkdir -p output
          nix-env -qaP '*' --json > output/packages.json
          # Можно добавить свою обработку: фильтры, markdown-описания и т.д.

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Update package metadata
            commit_user_email: dev@example.com
            commit_author: GitHub Actions <actions@example.com>
            push: true
            branch: main
