name: Update Package Metadata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # каждый день в 2:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y wget jq

      - name: Generate package metadata
        run: |
          mkdir -p output
          # пример генерации JSON, адаптируй под свои скрипты
          echo '{"packages": [{"name":"example","version":"1.0.0"}]}' > output/packages.json

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package metadata
          branch: main
          push_options: --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
