name: Update Nix packages metadata

on:
  schedule:
    - cron: '0 0 * * *'   # каждый день в 00:00 UTC
  workflow_dispatch:       # ручной запуск вручную

permissions:
  contents: write          # разрешаем пуш в репозиторий

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1. Установка Nix
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      # 2. Подготовка окружения
      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl wget jq brotli
     # 3. Добавление каналов
      - name: Add nixos channel
        run: |
          nix-channel --add https://nixos.org/channels/nixos-25.05 nixos
          nix-channel --update

      # 4. Генерация JSON-файла
      - name: Generate Nix packages JSON
        run: |
          mkdir -p output
          DATE=$(date +'%Y-%m-%d')
          FILE="output/packages-${DATE}.json"
          echo "Generating packages.json..."
          mkdir -p ~/.config/nix
          echo "allow-unfree = true" >> ~/.config/nix/nix.conf
          nix-env -qaP --json --meta > "$FILE"
          echo "Compressing..."
          brotli -f "$FILE"
          ls -lh output/

      # # 5. Коммит и пуш изменений
      # - name: Commit & Push
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "Update Nix packages metadata"
      #     file_pattern: output/
      #     branch: main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
  
      - name: Upload generated JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nix-packages-${{ steps.date.outputs.today }}
          path: output/packages-*.json.br
          retention-days: 30
